services:
  - type: worker
    name: email-agent-worker
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - fromDotEnv: true
